name: Java CI with Nushell UwU

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test_game:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        player: [1, 2]

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    - uses: hustcer/setup-nu@v3.8
      with:
        version: "0.87.1"
    
    - name: Save Player${{ matrix.player }}
      uses: actions/upload-artifact@v3
      with:
        name: Bot-${{ matrix.player }}-${{ github.sha }}
        path: Player${{ matrix.player }}/Player.java
