name: Java CI with Nushell UwU

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test_game:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        test: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
        
    outputs:
        game_run: ${{ steps.mark.outputs.did_ran }}
        

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    - uses: hustcer/setup-nu@v3.8
      with:
        version: "0.88"
    - name: Create Class 1
      run: javac Player1/*.java
    - name: Create Class 2
      run: javac Player2/*.java
    - name: Create Class 3
      run: javac Player3/*.java
    - name: Create Class 4
      run: javac Player4/*.java

    - name: Run Game
      shell: nu {0}
      run: |
        if ${{ matrix.test }} == 0 {
          try { java -jar Game.jar --gui=false Player1 Player2 Player3 Player4 out> game${{ matrix.test }}.log } catch {}
        } else {
          java -jar Game.jar --gui=false Player1 Player2 Player3 Player4 out> game${{ matrix.test }}.log
        }
        
     
      
    - name: Save Game log
      uses: actions/upload-artifact@v3
      with:
        name: games
        path: game${{ matrix.test }}.log
        
    - name: Determine game
      shell: nu {0}
      run: |
        open game${{ matrix.test }}.log --raw 
        | lines
        | last 72
        | split list ""
        | each {|playr|
          $playr 
          | parse "{key}: {val}"
          | transpose -r
          | into record
        }
        | save result${{ matrix.test }}.nuon
        print (open result${{ matrix.test }}.nuon)
    
    - name: Save result
      uses: actions/upload-artifact@v3
      with:
        name: results
        path: result${{ matrix.test }}.nuon
        
    - name: Show winner
      shell: nu {0}
      run: |
        open result${{ matrix.test }}.nuon
        | where survive == "true"
    - name: New Kids on the block won?
      shell: nu {0}
      run: |
        let winners = (open result${{ matrix.test }}.nuon
        | where survive == "true")

        if (["Player1" "Player2" ] | any {|p| $p in $winners.STAT }) {
        print $"${{ matrix.test }}: Success ($winners.STAT) won"
        } else {
        print $"${{ matrix.test }}: fail! ($winners.STAT) won"
        }
    - name: mark complete
      id: mark
      run: echo "did_ran=${{ toJson(matrix.test) }}" >> $GITHUB_OUTPUT

  generate_report:
    needs: test_game
    runs-on: ubuntu-latest

    steps:
      - uses: hustcer/setup-nu@v3.8
        with:
          version: "0.88"

      - name: Get Reports
        uses: actions/download-artifact@v3
        with:
          name: results
          
      - name: Create summary file
        shell: nu {0}
        run: |
          "" | save summary.md
          
      - name: generate Data
        shell: nu {0}
        run: |
          ls result*.nuon
          | get name
          | each {|run|
            open $run
          }
          | save data.nuon
      
      
      - name: Create runs results table
        shell: nu {0}
        run: |
          
          mut summary = (open summary.md --raw)
          let data = (open data.nuon)
          
          $summary ++= "\n# Test summary\n<table>\n<tr>"
          $summary ++= ($data
          | enumerate
          | each {|i|
            mut $out = ""
            if ($i.index mod 5 == 0) {
              $out ++= "</tr><tr>"
            }
          
            $out ++= $"<td>\n\nRun: ($i.index)\n($i.item 
            | select STAT survive 
            | to md )\n</td>"

            $out
          })
          
          $summary ++= "</tr></table>\n\n# Data\n\n"

          $summary | save summary.md --raw -f

      
      - name: Generate w/l graph
        shell: nu {0}
        run: |
          
          mut summary = (open summary.md --raw)
          let data = (open data.nuon)
          
          let grouped = ($data
          | enumerate
          | each {|i|
            $i.item | select STAT survive
            | upsert game $i.index
          }
          | flatten
          | into value
          )
          
          let players = ($grouped
          | where survive
          | group-by STAT
          | items {|k,v|
           {$k: ($v | length)}
          }
          | into record
          | flatten
          | into record)

          let sum = $players | values | reduce {|v,agg| $agg + $v}
          $summary ++= "|Player| Wins :white_check_mark: vs. Loses :x: |:white_check_mark: count|:x: count|\n|-|-|-|-|"
          $summary ++= ($players
          | items {|k,v|
            let wins = (""| fill -c "█" -w (($v / $sum ) * 120 | math round))
            let losses = (""| fill -c "░" -w (((10 - $v) / $sum ) * 120 | math round))
            $"|($k)|($wins)($losses)|($v)|(10 - $v)|"
          })
          
          $summary | save summary.md --raw -f

      
      - name: add raw data
        shell: nu {0}
        run: |
          
          mut summary = (open summary.md --raw)
          let data = (open data.nuon)
          
          $summary ++= ($data
          | enumerate
          | each {|i|
            $"
            ## Run ($i.index) data
            ($i.item | to md)
            "})

          $summary | save summary.md --raw -f

      
      - name: Generate summary
        shell: nu {0}
        run: |
          
          mut summary = (open summary.md --raw)
          let data = (open data.nuon)
          $summary 
            | str replace -a "true" ":white_check_mark:" 
            | str replace -a "false" ":x:"
            | save --raw summary.md -f
            
      - name: export to bash env
        run: cat summary.md >>  $GITHUB_STEP_SUMMARY
